const STORAGE_KEY='hanhan-fantawild-adventure-v1',DB_NAME='hanhan-adventure-media-v1',STORE='evidence';
const art={courage:'<svg viewBox="0 0 60 60"><path d="M12 50V13m2 2c13-8 20 7 34-2v20c-14 9-22-6-34 2"/><path d="M7 50h14M19 48l11-18 8 12 5-7 10 13"/></svg>',imagination:'<svg viewBox="0 0 60 60"><path d="m30 7 6 13 14 2-10 10 2 14-12-7-12 7 2-14-10-10 14-2z"/><circle cx="48" cy="10" r="3"/><path d="M9 39c7-5 12-5 18 0"/></svg>',partner:'<svg viewBox="0 0 60 60"><circle cx="18" cy="16" r="7"/><circle cx="43" cy="16" r="7"/><path d="M8 50V35c0-8 4-13 10-13s9 4 10 10l2 8 3-8c1-6 4-10 10-10s9 5 9 13v15M19 36l11 8 11-8"/></svg>',happy:'<svg viewBox="0 0 60 60"><rect x="8" y="10" width="44" height="39" rx="5"/><path d="M8 20h44M17 10v10M43 10v10"/><circle cx="22" cy="33" r="2" fill="currentColor" stroke="none"/><circle cx="38" cy="33" r="2" fill="currentColor" stroke="none"/><path d="M21 39c5 6 14 6 19 0"/></svg>',photo:'<svg viewBox="0 0 60 60"><path d="M9 18V9h9M42 9h9v9M51 42v9h-9M18 51H9v-9"/><rect x="15" y="17" width="30" height="27" rx="4"/><circle cx="30" cy="30" r="9"/><path d="m22 17 4-5h9l4 5"/></svg>'};
const stages=[
 {id:'courage',place:'第一站｜勇气山谷',name:'勇气山谷',map:'找到最勇敢的一刻',ask:'今天有没有一个东西，\n你本来有一点点害怕？',cheer:'勇敢去试试看！',question:'刚刚哪里让你觉得自己很勇敢？',photoLabel:'拍下勇敢时刻',badge:'勇气徽章',icon:'勇',photo:true,voice:true},
 {id:'imagination',place:'第二站｜神秘伙伴岛',name:'神秘伙伴岛',map:'找到最喜欢的伙伴',ask:'找到你今天最喜欢的伙伴，\n和TA拍一张照片吧！',cheer:'你想带TA去哪里玩？',question:'为什么你最喜欢TA？',photoLabel:'和神秘伙伴合影',badge:'想象力徽章',icon:'想',photo:true,voice:true},
 {id:'partner',place:'第三站｜最佳搭档站',name:'最佳搭档站',map:'这一次妈妈听你的',ask:'这一次，由你来选！\n妈妈陪你一起玩。',cheer:'你们是最棒的搭档！',question:'今天你和妈妈一起完成了什么？',photoLabel:'我和妈妈的冒险合影',badge:'最佳搭档徽章',icon:'伴',photo:true,voice:true},
 {id:'happy',place:'第四站｜哈哈森林',name:'哈哈森林',map:'抓住最好笑的一刻',ask:'今天什么时候，\n你和妈妈笑得最大声？',cheer:'把这份快乐收藏起来！',question:'今天什么事情让你笑得最大声？',photoLabel:'拍下快乐时刻',badge:'快乐徽章',icon:'乐',photo:true,voice:true,voiceFirst:true},
 {id:'photo',place:'第五站｜小小摄影屋',name:'小小摄影屋',map:'今天换你记录妈妈',ask:'平时都是妈妈记录你，\n今天换你来记录妈妈。',cheer:'让妈妈笑一个！',question:'给妈妈拍一张你最喜欢的照片吧！',photoLabel:'给妈妈拍一张照片',badge:'摄影师徽章',icon:'影',photo:true,voice:false,secret:true}
];
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return{completed:x?.completed||{}}}catch{return{completed:{}}}}
let state=load(),activeId=null,activeEvidence={},rewardTimer,mediaRecorder,mediaStream,recordTimer,recordChunks=[],activeUrls=[];
const $=s=>document.querySelector(s),mapStages=$('#map-stages'),layer=$('#challenge-layer'),reward=$('#reward-layer');
const dbReady=new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('IndexedDB unavailable'));return}const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function getEvidence(id){try{const db=await dbReady;return await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result||{id});r.onerror=()=>rej(r.error)})}catch{return{id}}}
async function putEvidence(record){try{const db=await dbReady;await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(record);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});return true}catch{return false}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function doneCount(){return stages.filter(s=>state.completed[s.id]).length}function secretOpen(){return stages.slice(0,4).filter(s=>state.completed[s.id]).length>=3}
function clearUrls(){activeUrls.forEach(URL.revokeObjectURL);activeUrls=[]}function blobUrl(blob){const u=URL.createObjectURL(blob);activeUrls.push(u);return u}
function stageTemplate(s){const done=!!state.completed[s.id],locked=s.secret&&!secretOpen();return `<button class="stage ${done?'completed':''} ${locked?'locked':''}" data-stage="${s.id}" type="button" aria-label="${locked?'神秘关卡，找到三枚徽章后开启':s.place}"><div class="stage-top"><span class="stage-art">${art[s.id]}</span><span><small>${s.secret?(locked?'神秘关卡':'神秘关卡已开启'):s.place.split('｜')[0]}</small><strong>${locked?'神秘关卡':s.name}</strong></span></div><p>${locked?'再找到一些徽章，就能看见这里！':s.map}</p></button>`}
function render(){mapStages.innerHTML=stages.map(stageTemplate).join('');const n=doneCount();$('#badge-count').textContent=n;$('#badge-dots').innerHTML=stages.map(s=>`<i class="badge-dot ${state.completed[s.id]?'on':''}">${s.icon}</i>`).join('');$('#road-fill').style.height=`${Math.min(100,n*21)}%`;const castle=$('#castle'),open=n>=3;castle.classList.toggle('locked',!open);castle.classList.toggle('unlocked',open);castle.setAttribute('aria-label',open?'秘密城堡已开启':'秘密城堡，完成三关后解锁');$('#castle-hint').textContent=open?'打开今天的冒险故事':'找到3枚徽章后开启'}
async function openStage(id){const s=stages.find(x=>x.id===id);if(s.secret&&!secretOpen())return;activeId=id;clearUrls();activeEvidence=await getEvidence(id);$('#challenge-illustration').innerHTML=art[id];$('#challenge-station').textContent=s.place;$('#challenge-title').textContent=s.name;$('#challenge-copy').innerHTML=s.ask.split('\n').map(x=>`<p>${x}</p>`).join('')+`<p>${s.cheer}</p>`;$('#evidence-question').textContent=s.question;$('#photo-actions').hidden=!s.photo;$('#camera-label').textContent=activeEvidence.photo?s.photoLabel.replace('拍下','重新拍下'):s.photoLabel;$('#voice-area').hidden=!s.voice;$('#voice-button').classList.remove('recording');$('#voice-button b').textContent=activeEvidence.audio?'重新录制':'说给我听';$('#record-status').textContent='';showEvidence();const btn=$('#success-button'),done=!!state.completed[id];btn.textContent=done?'取消点亮这一关':'我闯关成功啦！';btn.classList.toggle('done',done);layer.hidden=false;setTimeout(()=>btn.focus(),50)}
function showEvidence(){const p=activeEvidence.photo,a=activeEvidence.audio;$('#evidence-preview').hidden=!p;if(p)$('#photo-preview').src=blobUrl(p);$('#voice-preview').hidden=!a;if(a)$('#voice-preview').src=blobUrl(a)}
function closeStage(){if(mediaRecorder?.state==='recording')stopRecording();layer.hidden=true;activeId=null;clearUrls()}
function showReward(s){clearTimeout(rewardTimer);$('#reward-icon').textContent=s.icon;$('#reward-text').textContent=`获得${s.badge}！`;reward.hidden=false;rewardTimer=setTimeout(()=>reward.hidden=true,1500)}
async function compressImage(file){if(file.size>18*1024*1024)throw new Error('照片太大，请换一张');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1280/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return await new Promise(resolve=>canvas.toBlob(b=>resolve(b||file),'image/jpeg',.78))}catch{return file}finally{URL.revokeObjectURL(url)}}
async function handlePhoto(file){if(!file||!activeId)return;$('#record-status').textContent='正在保存照片…';try{const photo=await compressImage(file);activeEvidence={...activeEvidence,id:activeId,photo,photoType:photo.type,updatedAt:Date.now()};if(!await putEvidence(activeEvidence))throw new Error();clearUrls();showEvidence();$('#camera-label').textContent='重新拍一张';$('#record-status').textContent='照片保存好啦！'}catch{$('#record-status').textContent='这张照片没有保存成功，请再试一次'}finally{$('#camera-input').value='';$('#gallery-input').value=''}}
function supportedMime(){return['audio/mp4','audio/webm','audio/ogg'].find(t=>window.MediaRecorder?.isTypeSupported?.(t))||''}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('#record-status').innerHTML='<span class="record-unavailable">这个浏览器暂时不能录音，请用系统浏览器打开。</span>';return}try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];const mime=supportedMime(),opts=mime?{mimeType:mime}:undefined;mediaRecorder=new MediaRecorder(mediaStream,opts);mediaRecorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};mediaRecorder.onstop=async()=>{clearTimeout(recordTimer);mediaStream?.getTracks().forEach(t=>t.stop());const audio=new Blob(recordChunks,{type:mediaRecorder.mimeType||mime||'audio/webm'});activeEvidence={...activeEvidence,id:activeId,audio,audioType:audio.type,updatedAt:Date.now()};const ok=await putEvidence(activeEvidence);clearUrls();showEvidence();$('#voice-button').classList.remove('recording');$('#voice-button b').textContent='重新录制';$('#record-status').textContent=ok?'声音保存好啦！':'声音没有保存成功，请再试一次'};mediaRecorder.start();$('#voice-button').classList.add('recording');$('#voice-button b').textContent='点一下结束';$('#record-status').textContent='正在听你说…';recordTimer=setTimeout(stopRecording,30000)}catch{$('#record-status').innerHTML='<span class="record-unavailable">没有获得麦克风权限，可以跳过声音继续闯关。</span>'}}
function stopRecording(){if(mediaRecorder?.state==='recording')mediaRecorder.stop()}
async function renderStory(){clearUrls();const completed=stages.filter(s=>state.completed[s.id]);$('#story-count').textContent=completed.length;$('#story-badge-list').innerHTML=completed.map(s=>`<span class="story-badge"><i>${s.icon}</i>${s.badge}</span>`).join('');const box=$('#story-moment-list');box.innerHTML='<p class="story-loading">正在翻开今天的故事…</p>';const records=await Promise.all(completed.map(s=>getEvidence(s.id)));box.innerHTML=completed.map((s,i)=>{const e=records[i],photo=e.photo?`<div class="moment-photo"><img src="${blobUrl(e.photo)}" alt="${s.name}留下的照片"><span>${s.id==='photo'?'晗晗镜头里的妈妈':'这一站的冒险照片'}</span></div>`:'<div class="moment-empty">这一站认真玩了，没有停下来拍照</div>';const audio=e.audio?`<div class="moment-audio"><span>▶</span><audio controls src="${blobUrl(e.audio)}"></audio></div>`:'<p class="moment-no-audio">这一站没有留下声音</p>';return `<article class="story-moment"><h3>${s.place}</h3><p>${s.map}</p>${photo}${audio}</article>`}).join('')||'<p class="story-loading">地图上还没有故事，先去闯关吧！</p>'}
mapStages.addEventListener('click',e=>{const b=e.target.closest('[data-stage]');if(b)openStage(b.dataset.stage)});layer.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]'))closeStage()});$('#camera-button').addEventListener('click',()=>$('#camera-input').click());$('#gallery-button').addEventListener('click',()=>$('#gallery-input').click());$('#camera-input').addEventListener('change',e=>handlePhoto(e.target.files[0]));$('#gallery-input').addEventListener('change',e=>handlePhoto(e.target.files[0]));$('#voice-button').addEventListener('click',()=>mediaRecorder?.state==='recording'?stopRecording():startRecording());
$('#success-button').addEventListener('click',()=>{if(!activeId)return;const s=stages.find(x=>x.id===activeId),finishing=!state.completed[activeId];state.completed[activeId]=finishing;save();closeStage();render();if(finishing)showReward(s)});
$('#castle').addEventListener('click',async()=>{if(doneCount()<3)return;$('#adventure-page').hidden=true;$('#record-page').hidden=false;scrollTo(0,0);await renderStory()});$('#back-map').addEventListener('click',()=>{$('#record-page').hidden=true;$('#adventure-page').hidden=false;clearUrls();scrollTo(0,document.body.scrollHeight-600)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!layer.hidden)closeStage()});window.addEventListener('beforeunload',()=>mediaStream?.getTracks().forEach(t=>t.stop()));render();
